services:
  - type: web
    name: agendador-consultas
    runtime: image
    image:
      url: eclipse-temurin:17-jdk
    rootDir: agendador
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar